const { Console } = require("./console");

const console = new Console();
let binary = console.readNumber(`Dame un número inferior a 16 en binario (0/1): `);
let msg = `El número ${binary} binario corresponde con `;
let decimal = 0;
const firstBit = binary % 10;
decimal += firstBit;
binary -= firstBit;
binary /= 10;
const secondBit = binary % 10;
decimal += secondBit * 2;
binary -= secondBit;
binary /= 10;
const thirdBit = binary % 10;
decimal += thirdBit * 4;
binary -= thirdBit;
binary /= 10;
const fourthBit = binary;
decimal += fourthBit * 8;
binary -= fourthBit;
msg += `el número ${decimal} decimal`;
console.writeln(msg);
